//-----CADASTRAR USUÁRIO -------------/
POST http://localhost:3003/user/create 
Content-Type: application/json 

{
    "name": "Guilherme Consuelo",
    "email": "guilherme.dev@gmail.com",
    "password": "sfsfcvvcvdsdiysdsdi"
}


//OBTER TODOS OS USUÁRIOS -------------/
###
GET  http://localhost:3003/user/getAll 



//CRIAR POSTAGEM --------------------- /
###
POST http://localhost:3003/task/create 
Content-Type: application/json 

{
    "id": "",
    "photo": "foto número 2 do Romeu",
    "description": "Nessa foto eu estava em um evento no MASP",
    "type": "EVENT",
    "created_at": "14/04/23",
    "authorId": "d5dbfe8a-fb34-49f8-9a3f-67bbec8acb7a" 
}


//BUSCAR POSTAGEM POR ID --------------------- /

