//-----CADASTRAR USUÁRIO -------------/
POST http://localhost:3003/user/create 
Content-Type: application/json 

{
    "name": "Guilherme0005 Consuelo",
    "email": "fggfggfgfksdgukguilherme555.dev@gmail.com",
    "password": "sfsfcvvcvdsdiysdsdi"
}


//OBTER TODOS OS USUÁRIOS -------------/
###
GET  http://localhost:3003/user/getAll 



//CRIAR POSTAGEM --------------------- /
###
POST http://localhost:3003/task/create 
Content-Type: application/json 

{
    "id": "",
    "photo": "22c2foto número 2 do Romeu",
    "description": "Nessa foto eu estava em um evento no MASP",
    "type": "EVENT",
    "created_at": "14/04/23",
    "authorId": "018ff005-1c84-40cd-87ed-477f6fe72c1c" 
}


//BUSCAR POSTAGEM ------------------------------ /
###
GET  http://localhost:3003/task/searchPost/27255ea5-cc54-43b4-96f4-2bb73b7534a7


//CRIAR AMIGOS --------------------- /
###
POST http://localhost:3003/friend/create 
Content-Type: application/json 

{
    "id": "",
    "id_user": "4a7c6c78-5ad5-4cc3-b231-30be604f06bc",
    "id_friend": "53937135-41b8-493d-adb2-284df8d74c55"
}